name: Sync to Cloudflare KV

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Data Repo
        uses: actions/checkout@v4
        with:
          path: data

      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: 'open-xiv/assets-worker'

      - name: Checkout Worker Repo
        uses: actions/checkout@v4
        with:
          repository: 'open-xiv/assets-worker'
          token: ${{ steps.generate-token.outputs.token }}
          path: worker

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm --prefix ./worker install

      - name: Sync to Cloudflare KV
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          KV_NAMESPACE_ID: ${{ secrets.CF_KV_NAMESPACE_ID }}
          DATA_PATH: ./data
        run: node ./worker/src/upload.mts